CREATE TABLE IF NOT EXISTS items(
 id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
 name VARCHAR(255) NOT NULL,
 price INT NOT NULL,
 store_id UUID NOT NULL,
 image_url VARCHAR(255),
 stock INT DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);
